// <auto-generated />
using System;
using Logistics.Api.Shipments.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistics.Api.Shipments.Infrastructure.Migrations
{
    [DbContext(typeof(ShipmentsDbContext))]
    [Migration("20260323033517_InitialShipmentsSchema")]
    partial class InitialShipmentsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shipments")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistics.Api.Shipments.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_delivered_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledReason")
                        .HasColumnType("text")
                        .HasColumnName("cancelled_reason");

                    b.Property<decimal>("CodAmount")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("cod_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentHubCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("current_hub_code");

                    b.Property<Guid?>("CurrentHubId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_hub_id");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_status");

                    b.Property<decimal>("DeclaredValue")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("declared_value");

                    b.Property<string>("DeliveryNote")
                        .HasColumnType("text")
                        .HasColumnName("delivery_note");

                    b.Property<DateOnly?>("ExpectedDelivery")
                        .HasColumnType("date")
                        .HasColumnName("expected_delivery");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer")
                        .HasColumnName("height_cm");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<decimal>("InsuranceFee")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("insurance_fee");

                    b.Property<int?>("LengthCm")
                        .HasColumnType("integer")
                        .HasColumnName("length_cm");

                    b.Property<string>("MerchantCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("merchant_code");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("PackageDescription")
                        .HasColumnType("text")
                        .HasColumnName("package_description");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_address");

                    b.Property<string>("ReceiverDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiver_district");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receiver_phone");

                    b.Property<string>("ReceiverProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiver_province");

                    b.Property<string>("ReceiverWard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiver_ward");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_address");

                    b.Property<string>("SenderDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_district");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sender_name");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sender_phone");

                    b.Property<string>("SenderProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_province");

                    b.Property<string>("SenderWard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_ward");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_type");

                    b.Property<string>("ShipmentCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("shipment_code");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("shipping_fee");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total_fee");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tracking_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WeightGram")
                        .HasColumnType("integer")
                        .HasColumnName("weight_gram");

                    b.Property<int?>("WidthCm")
                        .HasColumnType("integer")
                        .HasColumnName("width_cm");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_shipments_created_at");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("ix_shipments_current_status");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_shipments_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("ix_shipments_merchant_id");

                    b.HasIndex("ReceiverPhone")
                        .HasDatabaseName("ix_shipments_receiver_phone");

                    b.HasIndex("ShipmentCode")
                        .IsUnique()
                        .HasDatabaseName("ix_shipments_shipment_code");

                    b.HasIndex("TrackingCode")
                        .IsUnique()
                        .HasDatabaseName("ix_shipments_tracking_code");

                    b.HasIndex("MerchantId", "CurrentStatus")
                        .HasDatabaseName("ix_shipments_merchant_status");

                    b.ToTable("shipments", "shipments");
                });

            modelBuilder.Entity("Logistics.Api.Shipments.Domain.Entities.TrackingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("from_status");

                    b.Property<string>("HubCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hub_code");

                    b.Property<Guid?>("HubId")
                        .HasColumnType("uuid")
                        .HasColumnName("hub_id");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("operator_name");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("to_status");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tracking_code");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_tracking_events_occurred_at");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_tracking_events_shipment_id");

                    b.HasIndex("TrackingCode")
                        .HasDatabaseName("ix_tracking_events_tracking_code");

                    b.ToTable("tracking_events", "shipments");
                });

            modelBuilder.Entity("Logistics.Api.Shipments.Domain.Entities.TrackingEvent", b =>
                {
                    b.HasOne("Logistics.Api.Shipments.Domain.Entities.Shipment", null)
                        .WithMany("TrackingEvents")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistics.Api.Shipments.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("TrackingEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
