// <auto-generated />
using System;
using Logistics.Api.Pricing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistics.Api.Pricing.Infrastructure.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260323030750_InitialPricingSchema")]
    partial class InitialPricingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistics.Api.Pricing.Domain.Entities.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseFee")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("base_fee");

                    b.Property<decimal>("CodFeePercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cod_fee_percent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("FromProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("from_province");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxWeightGram")
                        .HasColumnType("integer")
                        .HasColumnName("max_weight_gram");

                    b.Property<int>("MinWeightGram")
                        .HasColumnType("integer")
                        .HasColumnName("min_weight_gram");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("PerKgFee")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("per_kg_fee");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_type");

                    b.Property<string>("ToProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("to_province");

                    b.Property<string>("ZoneType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zone_type");

                    b.HasKey("Id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_pricing_rules_priority");

                    b.HasIndex("ServiceType", "IsActive")
                        .HasDatabaseName("ix_pricing_rules_service_type_is_active");

                    b.ToTable("pricing_rules", "pricing");
                });
#pragma warning restore 612, 618
        }
    }
}
