services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:5080
      API_INTERNAL_BASE_URL: http://host.docker.internal:5080
    ports:
      - "3001:3000"